server:
  port: 8080
  
info:
   build:
      artifact: "com.dhurba.newSpringBootProject"
      name: "springbootdemo"
      description: "first spring boot"
      version: "1.3.4"
      
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_everest_db
    username: root
    password: root@123     
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
